### ISSUE TITLE
plans to merge back into upstream?

### ISSUE THREAD

**Issue by stefanpenner** [canjs/can-simple-dom#10]
Curious if there are plans to merge back into upstream or are they some incompatibilities or divergence of goals that prevent this?

**Comment by matthewp** [comment]
There are incompatibilities, mostly around the way modules are loaded.  Possibly some divergence in goals, this fork adds some stuff that simple-dom doesn't (like setting the `class` attribute when `className` changes).  One of the goals of this fork is to get jQuery to load in Node and a Web Worker. So I would say the fork is a little less minimal than simple-dom.  I can see merging back with upstream if that is wanted by them and they will accept the changes.  But biggest problem right now is probably that we are using different conflicting module loaders
