### ISSUE TITLE
Input elements should have a `.value`

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-simple-dom#17]
I'm not sure about this.  But canjs's setter likes to check if `"value" in el` before setting `el.value= newVal`.

**Comment by justinbmeyer** [comment]
On second thought, I think the better solution is to change CanJS's tests to simply set attributes and not `.value`.

**Comment by DesignByOnyx** [comment]
I implemented this in here: https://github.com/canjs/can-simple-dom/pull/16/files#diff-5e2ff02eecef03634b5925b51f5e87f2R1. I tried my best to replicate the browser's behavior for the interaction between the value attribute, defaultValue property, value property.

**Comment by justinbmeyer** [comment]
Hmm. I'm not sure this sort of thing should be added. At least not directly. There are so many elements and behaviors. The inheriting path of elements is complex too. 

Let's talk on Monday about this.
