### ISSUE TITLE
Implement ownerDocument.defaultView - used by jQuery as of 2015-06-14

### ISSUE THREAD

**Issue by DesignByOnyx** [canjs/can-simple-dom#25]
jQuery fixed some bugs in IE and FF but relies on ownerDocument.defaultView.opener:

https://github.com/jquery/jquery/blob/99e8ff1baa7ae341e94bb89c3e84570c7c3ad9ea/src/css/var/getStyles.js

This might be better suited for can vdom and other environments that actually have a window object.

**Comment by DesignByOnyx** [comment]
This is a double whammy. In the same jQuery file located above, they call `getComputedStyle` on the "view" object - which is either window or elem.ownerDocument.defaultView. There needs to be a getComputedStyle method on the window which does not yet exist. Again, this is probably a vdom thing more than can-simple-dom.

**Comment by andrejewski** [comment]
jQuery [no longer assumes `defaultView` exists](https://github.com/jquery/jquery/blob/b14ce54334a568eaaa107be4c441660a57c3db24/src/css/var/getStyles.js#L9), however we still need to provide `getComputedStyle` on the window, which will be handled in `can-vdom` with issue https://github.com/canjs/can-vdom/issues/18.
