### ISSUE TITLE
Consider moving to commonjs

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-simple-dom#50]
Right now can-simple-dom has a build step to transpile from es6 to commonjs, we should consider just changing the source to commonjs to match other modules.
- [ ] make everything commonjs
- [ ] remove build step
- [ ] move `can-simple-dom.js` to top level
- [ ] move stuff in `lib/can-simple-dom` to top level `lib`
- [ ] fix all the references
- [ ] remove `System.directories.lib`

**Comment by matthewp** [comment]
HEAVY PLUS SIGN

**Comment by frank-dspeed** [comment]
@phillipskevin @matthewp i don't think that this is a good idea as far as i know the NodeJS Dev Cycles and Roadmaps you should vote for making all canjs modules es6 as standart.

Please follow up: http://node.green/ 
We The NodeJS Community have already full ES2016 Support 

maybe you will find also the following info importent for your consideration :)

![LTS Cycle NodeJS](https://github.com/nodejs/LTS/raw/master/schedule.png)
