### ISSUE TITLE
Enumerable/Configurable tests fail in IE9/IE10

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-simple-dom#61]
[These tests](https://github.com/canjs/can-simple-dom/blame/master/lib/test/element-test.js#L287-L312) fail in [IE9](https://saucelabs.com/beta/tests/c39ba348340945c59ea09632125c33c5/commands#46) and [IE10](https://saucelabs.com/beta/tests/4c361157cbee49daa0a057f28f10028e/commands#37) because `__proto__` isn't defined in those browsers. I think the tests need to use `option.constructor.prototype`.

**Comment by phillipskevin** [comment]
@bmomberger-bitovi pointed out, this should probably use `Object.getPrototypeOf(option);`, which _is_ supported in IE9+.

**Comment by bmomberger-bitovi** [comment]
It's standard in ES5, and I think we can take it for granted now since there are no browsers in wide use that don't support it (safari 5, iOS 5.1, Opera 10, Konq 4.6, IE 8 don't, according to caniuse, and we don't support any of those).
